import os


os.system("sudo apt-get install git -y")
os.system("sudo apt-get install golang -y")
os.system("sudo apt-get install perl -y")
os.system("sudo apt-get install python3 -y")
os.system("sudo apt-get install python2 -y")
os.system("sudo apt-get install python3-pip -y")
os.system("sudo apt-get install nodejs -y")
os.system("sudo apt-get install npm -y")
os.system("cd")
os.system("git clone https://github.com/hoaan1995/ZxCDDoS")
os.system("cd ZxCDDoS")
os.system("npm i requests")
os.system("npm i https-proxy-agent")
os.system("npm i crypto-random-string")
os.system("npm i events")
os.system("npm i fs")
os.system("npm i net")
os.system("npm i cloudscraper")
os.system("npm i request")
os.system("npm i hcaptcha-solver")
os.system("npm i randomstring")
os.system("npm i cluster")
os.system("npm i cloudflare-bypasser")
os.system("pip3 install -r requirements.txt")
os.system("wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb")
os.system("apt-get install ./google-chrome-stable_current_amd64.deb")
os.system("ulimit -n 999999")
os.system("chmod 777 *")
os.system("python3 c2.py")

